cargo clippy -- \
    -A clippy::all \
    -D clippy::cargo \
    -A clippy::cargo-common-metadata \
    -A clippy::multiple-crate-versions \
    -D clippy::get_unwrap \
    -D clippy::unwrap_used \
    -D clippy::expect_used \
    -D clippy::panicking_unwrap \
    -D clippy::unnecessary_unwrap \
    -D clippy::unwrap_in_result \
    -D clippy::expect_fun_call \
    -D clippy::expect_used \
    -D clippy::ok_expect \
    -D clippy::panic \
    -D clippy::indexing_slicing \
    -D clippy::unimplemented \